name: production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Run docker-compose build and up
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST_DEV }}
                  username: ${{ secrets.USER_DEV }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  key: ${{ secrets.SSH_DEV }}
                  script: |
                      cd var/www/sicorskiy.site/
                      git pull origin main
